# Generated by Django 3.1.2 on 2020-11-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=30)),
                ('nombre_invocador', models.CharField(max_length=15)),
                ('Liga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.liga')),
                ('servidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.server')),
            ],
        ),
    ]
