# Generated by Django 3.1.2 on 2020-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imagenes_galeria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenes_galeria',
            old_name='nombre',
            new_name='nombre_ima',
        ),
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria'),
        ),
    ]
