# Generated by Django 3.1.2 on 2020-11-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201117_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenes_galeria',
            name='imagen',
            field=models.ImageField(null=True, upload_to='galeria/'),
        ),
    ]
