# Generated by Django 3.1.2 on 2020-11-19 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201118_0148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aspirante',
            old_name='correo',
            new_name='correo_invocador',
        ),
    ]
