# Generated by Django 3.1.2 on 2020-11-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201119_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenes_galeria',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='galeria'),
        ),
    ]
